### ISSUE TITLE
Add button input

### ISSUE THREAD

**Issue by sommo** [widapro/pixel_led_mqtt_panel#15]
Hi,
Is it possible to add some buttons input to adjust light intensity, switch effect and maybe switch topic mqtt subscriptions ?
Thank you

**Comment by jcampoy** [comment]
this only needs home assistant configuration, you can use a selector combined with an automation, this example works for me:

```
input_number: 
  intensity_wled_blue:
    min: 0
    max: 15
    mode: slider
    icon: mdi:brightness-5
    name: Intensity wled_blue

automation:
  - id: set_wled_intensity
    alias: set the wled intensity
    trigger:
      - platform: state
        entity_id: input_number.intensity_wled_blue
    action:
      - service: mqtt.publish
        data_template:
          topic: wled_blue/intensity
          payload: "{{ trigger.to_state.state | int }}"
```
